# Generated by Django 4.2.9 on 2024-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0004_sign_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='date',
        ),
        migrations.AlterField(
            model_name='sign',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
