# Generated by Django 4.2.9 on 2024-01-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0005_remove_sign_date_alter_sign_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
